import type { ProposalArtifactType } from '@novel-enginner/services/domain/values';

import type { ProposalFormField, ProposalFormSpec } from './types';

const ENTITY_STATUS = ['active', 'inactive', 'archived'] as const;
const CANONICAL_STATUS = ['draft', 'approved', 'superseded', 'archived'] as const;
const BOOK_STATUS = ['planning', 'active', 'paused', 'completed', 'archived'] as const;
const CHAPTER_TYPES = ['progress', 'pressure', 'action', 'reveal', 'payoff', 'turn', 'transition'] as const;

type FieldOptions = Partial<Omit<ProposalFormField, 'name' | 'label' | 'type'>>;

const text = (name: string, label: string, options: FieldOptions = {}): ProposalFormField => ({ name, label, type: 'text', ...options });
const textarea = (name: string, label: string, options: FieldOptions = {}): ProposalFormField => ({ name, label, type: 'textarea', ...options });
const list = (name: string, label: string, options: FieldOptions = {}): ProposalFormField => ({ name, label, type: 'list', ...options });
const number = (name: string, label: string, options: FieldOptions = {}): ProposalFormField => ({ name, label, type: 'number', ...options });
const select = (name: string, label: string, options: readonly string[], fieldOptions: FieldOptions = {}): ProposalFormField => ({ name, label, type: 'select', options, ...fieldOptions });

const briefCommon = [
  text('bookId', '书 ID', { required: true, placeholder: 'book-local', helpText: '作品唯一标识。' }),
  text('title', '书名', { required: true }),
  list('genres', '题材', { required: true, placeholder: '科幻, 太空歌剧' }),
  text('targetAudience', '目标读者', { required: true }),
  text('marketScope', '市场范围', { required: true, placeholder: '中文网络连载市场' }),
  text('readerPromise', '读者承诺', { required: true }),
  textarea('corePremise', '核心前提', { required: true }),
  text('openingHook', '开篇钩子', { required: true }),
  list('contentBoundaries', '内容边界', { placeholder: '不剧透大结局' }),
  text('format', '连载形态', { required: true, placeholder: '连载长篇' }),
  select('status', '状态', CANONICAL_STATUS, { defaultValue: 'draft' }),
] as const;

export const ARTIFACT_FORM_SPECS: Readonly<Record<ProposalArtifactType, ProposalFormSpec>> = {
  'project-brief': {
    artifactType: 'project-brief',
    title: '项目简介',
    targetIdLabel: '简介 ID',
    targetIdPlaceholder: 'project-brief',
    bodySection: '定位',
    bodyLabel: '定位说明',
    fields: [
      ...briefCommon,
      list('sourceResearchEvidenceIds', '研究证据 ID', { placeholder: 'evidence-1, evidence-2' }),
      list('assumptionIds', '待验证假设 ID', { placeholder: 'assumption-001' }),
    ],
  },
  'world-foundation': {
    artifactType: 'world-foundation',
    title: '世界观基石',
    targetIdLabel: '世界观 ID',
    targetIdPlaceholder: 'world-foundation',
    bodySection: '世界观',
    bodyLabel: '世界观说明',
    fields: [
      text('bookId', '书 ID', { required: true, placeholder: 'book-local' }),
      text('eraAndPrimarySetting', '时代与主场景', { required: true }),
      text('realityMode', '现实模式', { required: true, placeholder: 'hard' }),
      text('tone', '基调', { required: true }),
      text('capabilitySystem', '能力系统', { required: true, placeholder: '无超能力' }),
      list('immutableRules', '不可变规则', { required: true }),
      text('socialOrder', '社会秩序', { required: true }),
      list('narrativeProhibitions', '叙事禁区', { required: true }),
      list('terminologyRefs', '术语引用', { placeholder: 'tech-tide-clock' }),
      text('projectBriefRef', '项目简介引用', { required: true, placeholder: 'project-brief' }),
      select('status', '状态', CANONICAL_STATUS, { defaultValue: 'draft' }),
    ],
  },
  'story-blueprint': {
    artifactType: 'story-blueprint',
    title: '故事蓝图',
    targetIdLabel: '蓝图 ID',
    targetIdPlaceholder: 'story-blueprint',
    bodySection: '主线',
    bodyLabel: '主线说明',
    fields: [
      text('bookId', '书 ID', { required: true, placeholder: 'book-local' }),
      text('projectBriefRef', '项目简介引用', { required: true, placeholder: 'project-brief' }),
      text('worldFoundationRef', '世界观引用', { required: true, placeholder: 'world-foundation' }),
      textarea('protagonistArc', '主角弧线', { required: true }),
      text('centralConflict', '核心冲突', { required: true }),
      text('opposition', '对立力量', { required: true }),
      text('resolutionDirection', '终局方向', { required: true }),
      list('volumePlan', '卷计划', { required: true, placeholder: '一卷完本' }),
      list('crossVolumeCommitments', '跨卷承诺', { required: true }),
      number('estimatedVolumeCount', '预计卷数', { required: true }),
      select('status', '状态', CANONICAL_STATUS, { defaultValue: 'draft' }),
    ],
  },
  'volume-outline': {
    artifactType: 'volume-outline',
    title: '卷纲',
    targetIdLabel: '卷 ID',
    targetIdPlaceholder: 'volume-001',
    bodySection: '卷纲',
    bodyLabel: '卷纲说明',
    fields: [
      text('title', '卷标题', { required: true }),
      select('status', '状态', BOOK_STATUS, { required: true, defaultValue: 'planning' }),
      number('sequenceNumber', '卷序号', { required: true }),
      textarea('goal', '卷目标', { required: true }),
      text('stage', '阶段', { required: true, placeholder: 'planning' }),
      list('chapterRoster', '章节清单', { placeholder: 'chapter-0001-outline' }),
      number('targetChapterCount', '目标章节数', { required: true }),
      list('requiredCluePayoffs', '必需伏笔回收', { placeholder: 'clue-lantern' }),
      list('milestones', '里程碑', { placeholder: 'pa-first-tide' }),
    ],
  },
  'chapter-outline': {
    artifactType: 'chapter-outline',
    title: '章节细纲',
    targetIdLabel: '细纲 ID',
    targetIdPlaceholder: 'chapter-0001-outline',
    bodySection: '细纲',
    bodyLabel: '细纲正文',
    fields: [
      number('chapterNumber', '章节序号', { required: true }),
      text('volumeId', '所属卷', { required: true, placeholder: 'volume-001' }),
      select('chapterType', '章节类型', CHAPTER_TYPES, { required: true }),
      list('chapterTypeTags', '类型标签', { placeholder: 'progress' }),
      text('displayTitle', '显示标题'),
      number('targetWordCount', '目标字数', { required: true }),
      {
        name: 'sceneSkeleton',
        label: '场景骨架',
        type: 'rows',
        required: true,
        columns: [
          { name: 'id', label: '场景 ID', type: 'text', placeholder: 'scene-0001' },
          { name: 'purpose', label: '目的', type: 'text' },
          { name: 'locationId', label: '地点 ID', type: 'text', placeholder: 'location-harbor' },
          { name: 'participantCharacterIds', label: '参与角色', type: 'list', placeholder: 'char-mira' },
        ],
      },
      list('emotionCurveStageIds', '情绪曲线阶段 ID', { required: true, placeholder: 'emotion-1, emotion-2, emotion-3, emotion-4' }),
      select('status', '状态', CANONICAL_STATUS, { defaultValue: 'draft' }),
    ],
  },
  'chapter-manuscript': {
    artifactType: 'chapter-manuscript',
    title: '章节正文',
    targetIdLabel: '正文 ID',
    targetIdPlaceholder: 'chapter-0001-manuscript',
    bodySection: '正文',
    scenes: true,
    fields: [
      number('chapterNumber', '章节序号', { required: true }),
      text('volumeId', '所属卷', { required: true, placeholder: 'volume-001' }),
      text('basedOnOutlineId', '基于细纲', { required: true, placeholder: 'chapter-0001-outline' }),
      text('displayTitle', '显示标题'),
      text('basedOnCanonicalVersion', '基于快照', { required: true, placeholder: 'snap-0001' }),
      select('status', '状态', CANONICAL_STATUS, { defaultValue: 'draft' }),
    ],
  },
  'character-update': {
    artifactType: 'character-update',
    title: '角色档案',
    targetIdLabel: '角色 ID',
    targetIdPlaceholder: 'char-mira',
    bodySection: '档案',
    bodyLabel: '角色档案',
    fields: [
      text('name', '姓名', { required: true }),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
      textarea('coreMotivation', '核心动机', { required: true }),
      textarea('worldview', '世界观', { required: true }),
      textarea('baselinePersonality', '基线性格'),
      list('hardConstraints', '硬约束'),
      textarea('goalState', '目标状态'),
      textarea('injuryState', '受伤状态'),
      text('techLevel', '技术水平', { required: true }),
    ],
  },
  'faction-update': {
    artifactType: 'faction-update',
    title: '势力',
    targetIdLabel: '势力 ID',
    targetIdPlaceholder: 'faction-harbor-wardens',
    bodySection: '势力',
    bodyLabel: '势力说明',
    fields: [
      text('name', '名称', { required: true }),
      text('type', '类型', { required: true }),
      textarea('goal', '目标', { required: true }),
      list('resourceIds', '资源', { placeholder: 'res-brass-key' }),
      list('relationshipIds', '关系', { placeholder: 'rel-mira-warden' }),
      list('knownByCharacters', '已知角色', { placeholder: 'char-mira' }),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
    ],
  },
  'location-update': {
    artifactType: 'location-update',
    title: '地点',
    targetIdLabel: '地点 ID',
    targetIdPlaceholder: 'location-harbor',
    bodySection: '地点',
    bodyLabel: '地点说明',
    fields: [
      text('name', '名称', { required: true }),
      text('type', '类型', { required: true, placeholder: 'city' }),
      text('parentLocation', '上级地点', { placeholder: 'location-harbor' }),
      text('controlFaction', '控制势力', { placeholder: 'faction-wardens' }),
      list('hazards', '危险'),
      list('accessRules', '访问规则'),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
    ],
  },
  'tech-rule-update': {
    artifactType: 'tech-rule-update',
    title: '技术规则',
    targetIdLabel: '技术规则 ID',
    targetIdPlaceholder: 'tech-tide-clock',
    bodySection: '规则',
    bodyLabel: '规则说明',
    fields: [
      text('name', '名称', { required: true }),
      text('tier', '层级', { required: true, placeholder: 'foundational' }),
      list('preconditions', '前置条件'),
      list('costs', '成本'),
      list('limits', '上限'),
      list('allowedEffects', '允许效果'),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
    ],
  },
  'fact-update': {
    artifactType: 'fact-update',
    title: '共享事实',
    targetIdLabel: '事实 ID',
    targetIdPlaceholder: 'fact-tide-lock',
    bodySection: '事实',
    bodyLabel: '事实说明',
    fields: [
      textarea('statement', '事实陈述', { required: true }),
      text('sourceRef', '来源', { required: true, placeholder: 'fact-tide-lock' }),
      text('visibility', '可见性', { required: true, placeholder: 'public' }),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
    ],
  },
  'relationship-update': {
    artifactType: 'relationship-update',
    title: '关系',
    targetIdLabel: '关系 ID',
    targetIdPlaceholder: 'rel-mira-warden',
    bodySection: '关系',
    bodyLabel: '关系说明',
    fields: [
      text('sourceRef', '来源实体', { required: true, placeholder: 'char-mira' }),
      text('targetRef', '目标实体', { required: true, placeholder: 'faction-harbor-wardens' }),
      textarea('relationType', '关系类型', { required: true }),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
    ],
  },
  'resource-update': {
    artifactType: 'resource-update',
    title: '资源',
    targetIdLabel: '资源 ID',
    targetIdPlaceholder: 'res-brass-key',
    bodySection: '资源',
    bodyLabel: '资源说明',
    fields: [
      text('name', '名称', { required: true }),
      text('resourceType', '资源类型', { required: true }),
      text('ownerRef', '所有者', { required: true, placeholder: 'faction-harbor-wardens' }),
      text('holderRef', '持有者', { required: true, placeholder: 'char-mira' }),
      select('status', '状态', ENTITY_STATUS, { required: true, defaultValue: 'active' }),
    ],
  },
  'world-change': {
    artifactType: 'world-change',
    title: '世界观变更',
    targetIdLabel: '变更 ID',
    targetIdPlaceholder: 'world-change',
    bodySection: '变更',
    fields: [],
  },
};
